[build]
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

# Redirect rules for SPA behavior and authentication
[[redirects]]
  # Protect the main dashboard - redirect to login if not authenticated
  from = "/"
  to = "/login.html"
  status = 302
  conditions = {Role = ["!authenticated"]}

[[redirects]]
  # API routes go to functions
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  # Serve the main dashboard for authenticated users
  from = "/"
  to = "/index.html"
  status = 200

[[redirects]]
  # Handle client-side routing (fallback to main page)
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://d3js.org; style-src 'self' 'unsafe-inline'; img-src 'self' data:; font-src 'self'; connect-src 'self' https://*.netlify.app /.netlify/functions/; frame-ancestors 'none';"

# Cache static assets
[[headers]]
  for = "/js/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/styles/*"
  [headers.values]
    Cache-Control = "public, max-age=3600, s-maxage=3600"

[[headers]]
  for = "/data/*"
  [headers.values]
    Cache-Control = "public, max-age=300, s-maxage=300"

# Environment variables template (these should be set in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "staging"